// prototype/gui/src/lib/components/ServiceCard.svelte
<script lang="ts">
  import { Play, Square, RotateCcw, Cpu, MemoryStick, Wifi } from 'lucide-svelte';
  import type { Service } from '$lib/stores/services';
  import { startService, stopService, restartService } from '$lib/stores/services';

  interface Props {
    service: Service;
  }

  const { service }: Props = $props();

  // ---------------------------------------------------------------- //
  // Derived                                                           //
  // ---------------------------------------------------------------- //

  const isRunning = $derived(service.status === 'running');
  const isStopped = $derived(service.status === 'stopped');
  const isTransitioning = $derived(
    service.status === 'starting' || service.status === 'stopping'
  );

  const statusLabel = $derived({
    running: 'Running',
    stopped: 'Stopped',
    starting: 'Starting…',
    stopping: 'Stopping…',
    warning: 'Warning',
    unknown: 'Unknown',
  }[service.status] ?? service.status);

  const memoryFormatted = $derived(() => {
    const mb = service.metrics.memory / 1_048_576;
    if (mb < 1) return `${Math.round(service.metrics.memory / 1024)} KB`;
    if (mb < 1024) return `${mb.toFixed(1)} MB`;
    return `${(mb / 1024).toFixed(2)} GB`;
  });

  const uptimeFormatted = $derived(() => {
    if (!service.uptime) return null;
    const h = Math.floor(service.uptime / 3600);
    const m = Math.floor((service.uptime % 3600) / 60);
    if (h > 0) return `${h}h ${m}m`;
    if (m > 0) return `${m}m`;
    return `${service.uptime}s`;
  });

  // ---------------------------------------------------------------- //
  // Actions                                                           //
  // ---------------------------------------------------------------- //

  async function handleStart() {
    await startService(service.id);
  }

  async function handleStop() {
    await stopService(service.id);
  }

  async function handleRestart() {
    await restartService(service.id);
  }
</script>

<article class="service-card" class:running={isRunning} class:stopped={isStopped} class:warning={service.status === 'warning'}>

  <!-- Header -->
  <header class="card-header">
    <div class="card-title">
      <div class="status-dot" aria-hidden="true"></div>
      <span class="service-name">{service.displayName}</span>
      {#if service.port}
        <span class="port-badge">:{service.port}</span>
      {/if}
    </div>
    <span class="version-badge">{service.version}</span>
  </header>

  <!-- Status row -->
  <div class="status-row">
    <span class="status-label" class:transitioning={isTransitioning}>
      {statusLabel}
    </span>
    {#if uptimeFormatted()}
      <span class="uptime">up {uptimeFormatted()}</span>
    {/if}
    {#if service.pid}
      <span class="pid font-mono">PID {service.pid}</span>
    {/if}
  </div>

  <!-- Metrics row -->
  <div class="metrics-row">
    <div class="metric">
      <Cpu size={12} />
      <div class="metric-bar-wrap">
        <div
          class="metric-bar"
          style:width="{Math.min(service.metrics.cpu, 100)}%"
          class:high={service.metrics.cpu > 75}
          class:warn={service.metrics.cpu > 50 && service.metrics.cpu <= 75}
        ></div>
      </div>
      <span class="metric-value">{service.metrics.cpu.toFixed(1)}%</span>
    </div>
    <div class="metric">
      <MemoryStick size={12} />
      <span class="metric-value">{memoryFormatted()}</span>
    </div>
    {#if service.metrics.connections !== undefined}
      <div class="metric">
        <Wifi size={12} />
        <span class="metric-value">{service.metrics.connections}</span>
      </div>
    {/if}
  </div>

  <!-- Error notice -->
  {#if service.error}
    <div class="error-notice">{service.error}</div>
  {/if}

  <!-- Actions -->
  <footer class="card-actions">
    <button
      class="btn-icon btn-start"
      onclick={handleStart}
      disabled={isRunning || isTransitioning}
      aria-label="Start {service.displayName}"
      title="Start"
    >
      <Play size={13} fill="currentColor" />
    </button>

    <button
      class="btn-icon btn-stop"
      onclick={handleStop}
      disabled={isStopped || isTransitioning}
      aria-label="Stop {service.displayName}"
      title="Stop"
    >
      <Square size={13} fill="currentColor" />
    </button>

    <button
      class="btn-icon btn-restart"
      onclick={handleRestart}
      disabled={isStopped || isTransitioning}
      aria-label="Restart {service.displayName}"
      title="Restart"
    >
      <RotateCcw size={13} class:spinning={isTransitioning} />
    </button>
  </footer>

</article>

<style>
  .service-card {
    background: var(--bg-surface);
    border: 1px solid var(--border-default);
    border-radius: var(--radius-lg);
    padding: var(--space-4);
    display: flex;
    flex-direction: column;
    gap: var(--space-3);
    transition: border-color var(--transition-fast), box-shadow var(--transition-fast);
    min-width: 200px;
  }

  .service-card:hover {
    border-color: var(--border-strong);
    box-shadow: var(--shadow-sm);
  }

  .service-card.running {
    border-color: rgba(34, 197, 94, 0.2);
  }

  .service-card.stopped {
    border-color: rgba(239, 68, 68, 0.15);
  }

  .service-card.warning {
    border-color: rgba(245, 158, 11, 0.2);
  }

  /* Header */
  .card-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: var(--space-2);
  }

  .card-title {
    display: flex;
    align-items: center;
    gap: var(--space-2);
    min-width: 0;
  }

  .status-dot {
    width: 8px;
    height: 8px;
    border-radius: var(--radius-full);
    flex-shrink: 0;
    background: var(--text-muted);
    transition: background var(--transition-normal);
  }

  .running .status-dot  { background: var(--status-running); box-shadow: 0 0 6px var(--status-running); }
  .stopped .status-dot  { background: var(--status-stopped); }
  .warning .status-dot  { background: var(--status-warning); box-shadow: 0 0 6px var(--status-warning); }

  .service-name {
    font-size: var(--font-size-md);
    font-weight: 600;
    color: var(--text-primary);
    white-space: nowrap;
  }

  .port-badge {
    font-family: var(--font-mono);
    font-size: var(--font-size-xs);
    color: var(--text-muted);
  }

  .version-badge {
    font-family: var(--font-mono);
    font-size: var(--font-size-xs);
    color: var(--text-secondary);
    background: var(--bg-elevated);
    border: 1px solid var(--border-default);
    border-radius: var(--radius-sm);
    padding: 2px 6px;
    white-space: nowrap;
    flex-shrink: 0;
  }

  /* Status row */
  .status-row {
    display: flex;
    align-items: center;
    gap: var(--space-3);
  }

  .status-label {
    font-size: var(--font-size-sm);
    font-weight: 500;
    color: var(--text-secondary);
  }

  .running .status-label  { color: var(--status-running); }
  .stopped .status-label  { color: var(--status-stopped); }
  .warning .status-label  { color: var(--status-warning); }

  .status-label.transitioning {
    animation: pulse 1s ease-in-out infinite;
    color: var(--text-secondary);
  }

  .uptime, .pid {
    font-size: var(--font-size-xs);
    color: var(--text-muted);
  }

  /* Metrics */
  .metrics-row {
    display: flex;
    gap: var(--space-3);
    flex-wrap: wrap;
  }

  .metric {
    display: flex;
    align-items: center;
    gap: var(--space-1);
    color: var(--text-muted);
    font-size: var(--font-size-xs);
  }

  .metric-bar-wrap {
    width: 48px;
    height: 4px;
    background: var(--bg-elevated);
    border-radius: var(--radius-full);
    overflow: hidden;
  }

  .metric-bar {
    height: 100%;
    background: var(--accent-blue);
    border-radius: var(--radius-full);
    transition: width var(--transition-normal);
  }

  .metric-bar.warn { background: var(--status-warning); }
  .metric-bar.high { background: var(--status-stopped); }

  .metric-value {
    color: var(--text-secondary);
    font-family: var(--font-mono);
    font-size: var(--font-size-xs);
  }

  /* Error */
  .error-notice {
    font-size: var(--font-size-xs);
    color: var(--status-stopped);
    background: var(--status-stopped-bg);
    border: 1px solid rgba(239, 68, 68, 0.2);
    border-radius: var(--radius-sm);
    padding: var(--space-1) var(--space-2);
    line-height: 1.4;
  }

  /* Actions */
  .card-actions {
    display: flex;
    gap: var(--space-2);
    padding-top: var(--space-1);
    border-top: 1px solid var(--border-default);
  }

  .btn-icon {
    display: flex;
    align-items: center;
    justify-content: center;
    width: 28px;
    height: 28px;
    border-radius: var(--radius-md);
    border: 1px solid var(--border-default);
    background: var(--bg-elevated);
    color: var(--text-secondary);
    cursor: pointer;
    transition: background var(--transition-fast), color var(--transition-fast), border-color var(--transition-fast);
  }

  .btn-icon:hover:not(:disabled) {
    border-color: var(--border-strong);
    color: var(--text-primary);
  }

  .btn-icon:disabled {
    opacity: 0.35;
    cursor: not-allowed;
  }

  .btn-start:hover:not(:disabled) {
    background: var(--status-running-bg);
    border-color: var(--status-running);
    color: var(--status-running);
  }

  .btn-stop:hover:not(:disabled) {
    background: var(--status-stopped-bg);
    border-color: var(--status-stopped);
    color: var(--status-stopped);
  }

  .btn-restart:hover:not(:disabled) {
    background: var(--accent-blue-dim);
    border-color: var(--accent-blue);
    color: var(--accent-blue);
  }

  @keyframes pulse {
    0%, 100% { opacity: 1; }
    50% { opacity: 0.5; }
  }

  :global(.spinning) {
    animation: spin 0.8s linear infinite;
  }

  @keyframes spin {
    from { transform: rotate(0deg); }
    to   { transform: rotate(360deg); }
  }
</style>

// src/frontend/src/components/shared/ServiceCard.vue
<template>
  <div class="svc-card" :class="[`svc-${statusText}`]">
    <!-- Header -->
    <div class="svc-header">
      <div class="svc-name-row">
        <span class="svc-status-dot" :class="`dot-${statusText}`" />
        <span class="svc-name">{{ service.displayName || service.name || service.id }}</span>
      </div>
      <el-tag :type="tagType" size="small" effect="dark" class="svc-badge">
        {{ statusText }}
      </el-tag>
    </div>

    <!-- Metrics (only when running) -->
    <div v-if="isRunning" class="svc-metrics">
      <!-- CPU bar -->
      <div class="metric-row">
        <span class="metric-label">CPU</span>
        <div class="metric-bar-wrap">
          <div class="metric-bar" :style="{ width: cpuBarWidth }">
            <div class="metric-bar-fill cpu-fill" :style="{ width: '100%' }" />
          </div>
        </div>
        <span class="metric-value">{{ cpuText }}</span>
      </div>

      <!-- RAM bar -->
      <div class="metric-row">
        <span class="metric-label">RAM</span>
        <div class="metric-bar-wrap">
          <div class="metric-bar" style="width: 100%">
            <div class="metric-bar-fill ram-fill" :style="{ width: ramBarWidth }" />
          </div>
        </div>
        <span class="metric-value">{{ formatMem(service.memoryBytes ?? 0) }}</span>
      </div>

      <!-- Uptime + PID -->
      <div class="svc-meta">
        <span class="meta-item">
          <span class="meta-label">uptime</span>
          <span class="meta-val">{{ formatUptime(service.uptimeSeconds ?? 0) }}</span>
        </span>
        <span class="meta-item" v-if="service.pid">
          <span class="meta-label">pid</span>
          <span class="meta-val">{{ service.pid }}</span>
        </span>
        <span class="meta-item" v-if="service.version">
          <span class="meta-label">v</span>
          <span class="meta-val">{{ service.version }}</span>
        </span>
      </div>
    </div>

    <div v-else class="svc-offline">
      <span v-if="statusText === 'crashed'" class="offline-crashed">Process crashed</span>
      <span v-else-if="statusText === 'starting'" class="offline-starting">Starting...</span>
      <span v-else class="offline-stopped">Service not running</span>
      <span class="meta-item" v-if="service.version" style="margin-top: 4px;">
        <span class="meta-label">v</span>
        <span class="meta-val">{{ service.version }}</span>
      </span>
    </div>

    <!-- Actions -->
    <div class="svc-actions">
      <el-button
        size="small"
        type="success"
        plain
        :disabled="isRunning || busy"
        :loading="busy && pendingAction === 'start'"
        @click="act('start')"
      >
        Start
      </el-button>
      <el-button
        size="small"
        type="danger"
        plain
        :disabled="isStopped || busy"
        :loading="busy && pendingAction === 'stop'"
        @click="act('stop')"
      >
        Stop
      </el-button>
      <el-button
        size="small"
        plain
        :disabled="isStopped || busy"
        :loading="busy && pendingAction === 'restart'"
        @click="act('restart')"
      >
        Restart
      </el-button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue'
import { ElMessage, ElNotification } from 'element-plus'
import { useServicesStore } from '../../stores/services'

const props = defineProps<{ service: any }>()
const servicesStore = useServicesStore()
const pendingAction = ref<'start' | 'stop' | 'restart' | null>(null)

const busy = computed(() => servicesStore.isBusy(props.service.id))

const stateLabels: Record<number, string> = {
  0: 'stopped', 1: 'starting', 2: 'running', 3: 'stopping', 4: 'crashed', 5: 'disabled',
}
const statusText = computed(() => stateLabels[props.service.state] ?? props.service.status ?? 'unknown')
const isRunning = computed(() => props.service.state === 2)
const isStopped = computed(() => props.service.state === 0 || props.service.state === 5)

const tagType = computed((): '' | 'success' | 'warning' | 'danger' | 'info' => {
  const map: Record<string, '' | 'success' | 'warning' | 'danger' | 'info'> = {
    running: 'success', stopped: 'info', starting: 'warning',
    stopping: 'warning', crashed: 'danger', disabled: 'info',
  }
  return map[statusText.value] ?? 'info'
})

const cpuPercent = computed(() => Math.min(props.service.cpuPercent ?? 0, 100))
const cpuText = computed(() => `${cpuPercent.value.toFixed(1)}%`)
const cpuBarWidth = computed(() => `${cpuPercent.value}%`)

// RAM bar: cap display at 500 MB for visual scale
const RAM_MAX = 500 * 1024 * 1024
const ramBarWidth = computed(() => {
  const pct = Math.min((props.service.memoryBytes ?? 0) / RAM_MAX, 1) * 100
  return `${pct}%`
})

async function act(action: 'start' | 'stop' | 'restart') {
  pendingAction.value = action
  try {
    await servicesStore[action](props.service.id)
    const svcName = props.service.displayName || props.service.id
    ElMessage.success(`${svcName}: ${action} succeeded`)
  } catch (err: unknown) {
    const svcName = props.service.displayName || props.service.id
    const message = err instanceof Error ? err.message : String(err)
    ElNotification({
      title: `${svcName} — ${action} failed`,
      message,
      type: 'error',
      duration: 5000,
    })
  } finally {
    pendingAction.value = null
  }
}

function formatMem(bytes: number): string {
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(0)} KB`
  if (bytes < 1024 * 1024 * 1024) return `${(bytes / 1024 / 1024).toFixed(1)} MB`
  return `${(bytes / 1024 / 1024 / 1024).toFixed(2)} GB`
}

function formatUptime(seconds: number): string {
  if (seconds < 60) return `${seconds}s`
  if (seconds < 3600) return `${Math.floor(seconds / 60)}m ${seconds % 60}s`
  const h = Math.floor(seconds / 3600)
  const m = Math.floor((seconds % 3600) / 60)
  return `${h}h ${m}m`
}
</script>

<style scoped>
.svc-card {
  background: var(--wdc-surface);
  border: 1px solid var(--el-border-color);
  border-radius: 10px;
  padding: 16px;
  display: flex;
  flex-direction: column;
  gap: 12px;
  transition: border-color 0.15s, box-shadow 0.15s;
  border-top-width: 3px;
}

.svc-card:hover {
  box-shadow: 0 4px 16px rgba(0,0,0,0.25);
}

.svc-running  { border-top-color: var(--wdc-status-running); }
.svc-stopped  { border-top-color: var(--wdc-status-stopped); }
.svc-crashed  { border-top-color: var(--wdc-status-error); }
.svc-starting { border-top-color: var(--wdc-status-starting); }
.svc-stopping { border-top-color: var(--wdc-status-starting); }
.svc-disabled { border-top-color: var(--el-border-color); }
.svc-unknown  { border-top-color: var(--el-border-color); }

.svc-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.svc-name-row {
  display: flex;
  align-items: center;
  gap: 8px;
}

.svc-status-dot {
  width: 8px;
  height: 8px;
  border-radius: 50%;
  flex-shrink: 0;
}

.dot-running  { background: var(--wdc-status-running); box-shadow: 0 0 6px var(--wdc-status-running); }
.dot-stopped  { background: var(--wdc-status-stopped); }
.dot-crashed  { background: var(--wdc-status-error); box-shadow: 0 0 6px var(--wdc-status-error); }
.dot-starting { background: var(--wdc-status-starting); animation: pulse 1s infinite; }
.dot-stopping { background: var(--wdc-status-starting); animation: pulse 1s infinite; }
.dot-disabled { background: var(--el-border-color); }
.dot-unknown  { background: var(--el-border-color); }

@keyframes pulse {
  0%, 100% { opacity: 1; }
  50% { opacity: 0.4; }
}

.svc-name {
  font-size: 0.9rem;
  font-weight: 600;
  color: var(--el-text-color-primary);
}

.svc-badge { flex-shrink: 0; }

.svc-metrics {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.metric-row {
  display: flex;
  align-items: center;
  gap: 8px;
}

.metric-label {
  font-size: 0.72rem;
  color: var(--el-text-color-secondary);
  width: 28px;
  text-transform: uppercase;
  letter-spacing: 0.04em;
  flex-shrink: 0;
}

.metric-bar-wrap {
  flex: 1;
  height: 6px;
  background: var(--wdc-elevated, #242736);
  border-radius: 3px;
  overflow: hidden;
}

.metric-bar {
  height: 100%;
  border-radius: 3px;
  overflow: hidden;
}

.metric-bar-fill {
  height: 100%;
  border-radius: 3px;
  transition: width 0.4s ease;
}

.cpu-fill { background: linear-gradient(90deg, #3b82f6, #8b5cf6); }
.ram-fill { background: linear-gradient(90deg, #10b981, #06b6d4); }

.metric-value {
  font-size: 0.75rem;
  font-family: monospace;
  color: var(--el-text-color-regular);
  width: 52px;
  text-align: right;
  flex-shrink: 0;
}

.svc-meta {
  display: flex;
  gap: 12px;
  flex-wrap: wrap;
  margin-top: 4px;
}

.meta-item {
  display: inline-flex;
  align-items: center;
  gap: 4px;
}

.meta-label {
  font-size: 0.68rem;
  color: var(--el-text-color-secondary);
  text-transform: uppercase;
  letter-spacing: 0.04em;
}

.meta-val {
  font-size: 0.72rem;
  font-family: monospace;
  color: var(--el-text-color-regular);
}

.svc-offline {
  display: flex;
  flex-direction: column;
  gap: 4px;
  min-height: 42px;
  justify-content: center;
}

.svc-actions {
  display: flex;
  gap: 6px;
}

.svc-actions .el-button {
  flex: 1;
  font-size: 0.78rem;
}

.offline-crashed  { font-size: 0.78rem; color: var(--wdc-status-error); }
.offline-starting { font-size: 0.78rem; color: var(--wdc-status-starting); }
.offline-stopped  { font-size: 0.78rem; color: var(--wdc-text-3); }
</style>
